version: '3.7'
services:
  web:
    image: hesoyam-client
    container_name: b_client
    build:
      context: .
      dockerfile: Production.Dockerfile
      target: production
    environment:
      - CONTEXT=hesoyam-client
      - PORT=150
    ports:
      - '100:150'
